config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :vinos
  resources :cepas

  root 'vinos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cepa.rb
class Cepa < ApplicationRecord
    has_many :cepa_vinos
    has_many :vinos, through: :cepa_vinos
end

app/models/cepa_vino.rb
class CepaVino < ApplicationRecord
  belongs_to :cepa
  belongs_to :vino
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vino.rb
class Vino < ApplicationRecord
    has_many :cepa_vinos
    has_many :cepas, through: :cepa_vinos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authorize_editor!
        unless current_user.editor?
            flash[:alert]= 'you must be an editor to acces this section'
            redirect_to root_path
        end
    end
end

app/controllers/cepas_controller.rb
class CepasController < ApplicationController
  before_action :authorize_editor!
  before_action :set_cepa, only: %i[ show edit update destroy ]

  # GET /cepas or /cepas.json
  def index
    @cepas = Cepa.all
  end

  # GET /cepas/1 or /cepas/1.json
  def show
  end

  # GET /cepas/new
  def new
    @cepa = Cepa.new
  end

  # GET /cepas/1/edit
  def edit
  end

  # POST /cepas or /cepas.json
  def create
    @cepa = Cepa.new(cepa_params)

    respond_to do |format|
      if @cepa.save
        format.html { redirect_to cepa_url(@cepa), notice: "Cepa was successfully created." }
        format.json { render :show, status: :created, location: @cepa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cepa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cepas/1 or /cepas/1.json
  def update
    respond_to do |format|
      if @cepa.update(cepa_params)
        format.html { redirect_to cepa_url(@cepa), notice: "Cepa was successfully updated." }
        format.json { render :show, status: :ok, location: @cepa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cepa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cepas/1 or /cepas/1.json
  def destroy
    @cepa.destroy

    respond_to do |format|
      format.html { redirect_to cepas_url, notice: "Cepa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cepa
      @cepa = Cepa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cepa_params
      params.require(:cepa).permit(:name)
    end
end

app/controllers/vinos_controller.rb
class VinosController < ApplicationController
  before_action :set_vino, only: %i[ show edit update destroy ]

  # GET /vinos or /vinos.json
  def index
    @vinos = Vino.all
  end

  # GET /vinos/1 or /vinos/1.json
  def show
  end

  # GET /vinos/new
  def new
    @vino = Vino.new
  end

  # GET /vinos/1/edit
  def edit
  end

  # POST /vinos or /vinos.json
  def create
    @vino = Vino.new(name: vino_params[:name])

    respond_to do |format|
      if @vino.save
        vino_params[:cepa_ids].reject(&:empty?).each_with_index do |id, index|
          CepaVino.create!(vino_id: @vino.id, cepa_id: id, percentage: vino_params[:percentages][index])
        end
        format.html { redirect_to vino_url(@vino), notice: "Vino was successfully created." }
        format.json { render :show, status: :created, location: @vino }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vino.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vinos/1 or /vinos/1.json
  def update
    respond_to do |format|
      if @vino.update(vino_params)
        format.html { redirect_to vino_url(@vino), notice: "Vino was successfully updated." }
        format.json { render :show, status: :ok, location: @vino }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vino.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vinos/1 or /vinos/1.json
  def destroy
    @vino.destroy

    respond_to do |format|
      format.html { redirect_to vinos_url, notice: "Vino was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vino
      @vino = Vino.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vino_params
      params.require(:vino).permit(:name, cepa_ids: [], percentages: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cepas_helper.rb
module CepasHelper
end

app/helpers/vinos_helper.rb
module VinosHelper
end

app/views/cepas/_form.html.erb
<%= form_with(model: cepa, local: true) do |form| %>
  <% if cepa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cepa.errors.count, "error") %> prohibited this cepa from being saved:</h2>

      <ul>
      <% cepa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cepas/edit.html.erb
<h1>Editing Cepa</h1>

<%= render 'form', cepa: @cepa %>

<%= link_to 'Show', @cepa %> |
<%= link_to 'Back', cepas_path %>

app/views/cepas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cepas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cepas.each do |cepa| %>
      <tr>
        <td><%= cepa.name %></td>
        <td><%= link_to 'Show', cepa %></td>
        <td><%= link_to 'Edit', edit_cepa_path(cepa) %></td>
        <td><%= link_to 'Destroy', cepa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cepa', new_cepa_path %>

app/views/cepas/new.html.erb
<h1>New Cepa</h1>

<%= render 'form', cepa: @cepa %>

<%= link_to 'Back', cepas_path %>

app/views/cepas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cepa.name %>
</p>
<p>
  <h1>Cepas<h1>
  <ul>
    <% @cepa.vinos.each do |vino| %>
      <li><%= vino.name %></li>
    <% end %>
  <ul>
<p>

<%= link_to 'Edit', edit_cepa_path(@cepa) %> |
<%= link_to 'Back', cepas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cepas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>

        
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to 'Vinos', vinos_path, class: "navbar-brand" %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Cepas', cepas_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
        
    <%= yield %>
    
  </body>
</html>

app/views/vinos/_form.html.erb
<%= form_with(model: vino, local: true) do |form| %>
  <% if vino.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vino.errors.count, "error") %> prohibited this vino from being saved:</h2>

      <ul>
      <% vino.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <table>
    <div class="field">
      <%= form.label :cepas %>
      <%= form.collection_check_boxes(:cepa_ids, Cepa.all, :id, :name) do |b| %>
        <%= b.label class: 'label-checkbox' do %>
        <%= b.check_box + b.text %>
        <br>
        <%= form.text_field '', name:'vino[percentages][]' %>
        <% end %>
      <% end %>
    </div>
  </table>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vinos/edit.html.erb
<h1>Editing Vino</h1>

<%= render 'form', vino: @vino %>

<%= link_to 'Show', @vino %> |
<%= link_to 'Back', vinos_path %>

app/views/vinos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Vinos</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cepas</th>
      <th>aviable</th>
      <th>cepa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vinos.each do |vino| %>
      <tr>
        <td><%= vino.name %></td>
        <td>
            <ul>

            <%= vino.cepa_vinos.each do |cepa_vino| %>
                <li><%= cepa_vino.cepa.name %></li>
                <li><%= cepa_vino.cepa.aviable %></li>
                <li><%= vino.cepas.map(&:name).join('.') %></li>
            <% end %>
            </ul>
        </td>
        <td><%= link_to 'Show', vino %></td>
        <td><%= link_to 'Edit', edit_vino_path(vino) %></td>
        <td><%= link_to 'Destroy', vino, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vino', new_vino_path %>

app/views/vinos/new.html.erb
<h1>New Vino</h1>

<%= render 'form', vino: @vino %>

<%= link_to 'Back', vinos_path %>

app/views/vinos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vino.name %>
</p>
<p>
  <h1>Géneros<h1>
  <ul>
    <% @vino.cepas.each do |cepa| %>
      <li><%= cepa.name %></li>
    <% end %>
  <ul>
<p>

<%= link_to 'Edit', edit_vino_path(@vino) %> |
<%= link_to 'Back', vinos_path %>